update to new galaxy version

diff --git a/templates/install-tools.17.sh.j2 b/templates/install-tools.17.sh.j2
--- a/templates/install-tools.17.sh.j2
+++ b/templates/install-tools.17.sh.j2
@@ -7,7 +7,7 @@
 # author: Tangaro Marco
 # email: ma.tangaro@ibiom.cnr.it
 
-# Script based on install_tools_wrapper from B. Gruening and adpted to our ansible roles.
+# Script based on install_tools_wrapper from B. Gruening and adpted to our ansible roles.
 # https://raw.githubusercontent.com/bgruening/docker-galaxy-stable/master/galaxy/install_tools_wrapper.sh
 
 # Usage: install-tools GALAXY_ADMIN_API_KEY tool-list.yml
@@ -18,8 +18,6 @@ GALAXY_USER='{{galaxy_user}}'
 now=$(date +"%b-%d-%y-%H%M%S")
 install_log="/var/log/galaxy/galaxy_tools_install_$now.log"
 install_pidfile='/var/log/galaxy/galaxy_tools_install.pid'
-#---
-postgresql_version='9.6'
 #---
 ephemeris_version='{{ephemeris_version}}'
 
@@ -35,18 +33,17 @@ function start_postgresql_vm {
 
   if [[ $ID = "ubuntu" ]]; then
     echo "[Ubuntu][VM] Check postgresql."
-    if [[ $VERSION_ID = "16.04" ]]; then
-      service start postgresql
+    if [[ $VERSION_ID = "14.04" ]]; then
+      service postgresql start
     else
       systemctl start postgresql
     fi
   elif [[ $ID = "centos" ]]; then
       echo "[EL][VM] Check postgresql"
-      systemctl start postgresql-${postgresql_version}
+      systemctl start postgresql-9.6
   fi
 }
 
-#________________________________
 function start_postgresql_docker {
 
   if [[ $ID = "ubuntu" ]]; then
@@ -54,29 +51,27 @@ function start_postgresql_docker {
     service start postgresql
   elif [ "$ID" = "centos" ]; then
     echo "[EL][Docker] Check postgresql"
-    if [[ ! -f /var/lib/pgsql/${postgresql_version}/data/postmaster.pid ]]; then
+    if [[ ! -f /var/lib/pgsql/9.6/data/postmaster.pid ]]; then
       echo "Starting postgres on centos"
-      sudo -E -u postgres /usr/pgsql-${postgresql_version}/bin/pg_ctl -D /var/lib/pgsql/${postgresql_version}/data -w start
+      sudo -E -u postgres /usr/pgsql-9.6/bin/pg_ctl -D /var/lib/pgsql/9.6/data -w start
     fi
   fi
 
 }
 
-#________________________________
 function check_postgres_status {
 
   PGUSER="${PGUSER:="postgres"}"
 
   if [[ $ID = "ubuntu" ]]; then
-    echo 'placeholder'
+    /usr/lib/postgresql/9.6/bin/pg_isready -U "$PGUSER" -q
   elif [ "$ID" = "centos" ]; then
-    /usr/pgsql-${postgresql_version}/bin/pg_isready -U "$PGUSER" -q
-    DATA=$?
+    /usr/pgsql-9.6/bin/pg_isready -U "$PGUSER" -q
   fi
 
+  DATA=$?
 }
 
-#________________________________
 function check_postgresql {
 
 {% if ansible_virtualization_type == "docker" %}
@@ -124,17 +119,10 @@ function install_ephemeris {
 }
 
 #________________________________
-#________________________________
-#________________________________
-# Main section
-
 # clean logs
 echo "Clean logs"
 rm $install_log
 rm $install_pidfile
-
-# install tools
-install_ephemeris
 
 # ensure Galaxy is not running through supervisord
 if pgrep "supervisord" > /dev/null
@@ -158,14 +146,34 @@ sudo -E -u $GALAXY_USER touch $install_log
 # start Galaxy
 export PORT=8080
 echo "starting Galaxy"
-sudo -E -u $GALAXY_USER $GALAXY/run.sh -d $install_log --pidfile $install_pidfile  --http-timeout 3000
+sudo -E -u $GALAXY_USER $GALAXY/run.sh --daemon --log-file=$install_log --pid-file=$install_pidfile
 
 # wait galaxy to start
 galaxy_install_pid=`cat $install_pidfile`
-galaxy-wait -g http://localhost:$PORT -v --timeout 120
+echo $galaxy_install_pid
+
+while : ; do
+  tail -n 2 $install_log | grep -E -q "Removing PID file galaxy_install.pid|Daemon is already running"
+  if [ $? -eq 0 ] ; then
+    echo "Galaxy could not be started."
+    echo "More information about this failure may be found in the following log snippet from galaxy_install.log:"
+    echo "========================================"
+    tail -n 60 $install_log
+    echo "========================================"
+    echo $1
+    exit 1
+  fi
+  tail -n 2 $install_log | grep -q "Starting server in PID $galaxy_install_pid"
+  if [ $? -eq 0 ] ; then
+    echo "Galaxy is running."
+    break
+  fi
+done
 
 # install tools
-shed-tools install -g "http://localhost:$PORT" -a $1 -t "$2"
+install_ephemeris
+
+shed-install -g "http://localhost:$PORT" -a $1 -t "$2"
 
 exit_code=$?
 
@@ -175,7 +183,7 @@ fi
 
 # stop Galaxy
 echo "stopping Galaxy"
-sudo -E -u $GALAXY_USER $GALAXY/run.sh --stop $install_pidfile
+sudo -E -u $GALAXY_USER $GALAXY/run.sh --stop-daemon --log-file=$install_log --pid-file=$install_pidfile
 
 {% if ansible_virtualization_type == "docker" %}
 # stop postgresql on docker. Keep it running on vm
@@ -184,6 +192,7 @@ if [[ $ID = "ubuntu" ]]; then
   service stop postgresql
 elif [[ $ID = "centos" ]]; then
   echo "[EL][Docker] Stop postgresql"
-  sudo -Hiu postgres /usr/pgsql-${postgresql_version}/bin/pg_ctl -D /var/lib/pgsql/${postgresql_version}/data stop
+  sudo -E -u postgres /usr/pgsql-9.6/bin/pg_ctl -D /var/lib/pgsql/9.6/data stop
 fi
+
 {% endif %}
